sudo: false
notifications:
  email: false

#
# Describe the overall env.
#
language: node_js

#
# Cache the composer and node_modules directory to speed up the the installation of dependencies.
#
cache:
  directories:
    - node_modules

#
# Parallel environments, the value represents the name of the shell script which needs to be placed in `Build/TravisCi/Scripts/[name].sh`.
#
env:
  - TEST_SUITE=CodeStyle
  - TEST_SUITE=UnitTests

#
# Execute the test environment specific shell script.
#
script:
  - if [ -f "Build/TravisCi/Scripts/$TEST_SUITE.sh" ]; then bash Build/TravisCi/Scripts/$TEST_SUITE.sh; fi

#
# Execute the test environment specific after_script shell script.
#
#after_script:
  #- npm run coverage:generate && npm run coverage:publish
