TYPO3:
  Flow:
    security:
      authentication:
        providers:
          Typo3BackendProvider:
            requestPatterns:
              controllerObjectName: 'PackageFactory\Guevara\Controller\.*|TYPO3\Neos\Controller\.*|TYPO3\Neos\Service\.*|TYPO3\Media\Controller\.*'
  Neos:
    typoScript:
      autoInclude:
        'PackageFactory.Guevara': TRUE

  TypoScript:
    defaultContext:
      'Guevara.Activation': 'PackageFactory\Guevara\TypoScript\Helper\ActivationHelper'
PackageFactory:
    Guevara:
      changes:
        types:
            'PackageFactory.Guevara:Property': 'PackageFactory\Guevara\Domain\Model\Changes\Property'
            'PackageFactory.Guevara:Create': 'PackageFactory\Guevara\Domain\Model\Changes\Create'
